run:
  go: "1.21"

linters:
  enable-all: true
  disable:
    - copyloopvar
    - cyclop
    - depguard
    - exhaustive
    - exhaustruct
    - gci
    - gochecknoinits
    - gomoddirectives
    - intrange
    - ireturn
    - lll
    - nestif
    - nlreturn
    - nonamedreturns
    - varnamelen
    # deprecated
    - bodyclose
    - contextcheck
    - execinquery
    - gomnd
    - nilerr
    - noctx
    - rowserrcheck
    - sqlclosecheck
    - tparallel
    - unparam
    - wastedassign

linters-settings:
  revive:
    rules:
      - name: line-length-limit
        arguments: [120]

  funlen:
    lines: 100

  gosec:
    excludes:
      - G204

  nolintlint:
    require-specific: true

  mnd:
    ignored-numbers:
      ["2", "10", "100", "128", "1000", "100.0", "0o600", "0o755"]

issues:
  include:
    - EXC0002

  exclude-rules:
    - path: _test.go
      linters:
        - funlen
        - gocyclo
        - gochecknoglobals
        - gocognit
        - paralleltest
        - dupl
        - maintidx
