name: CI

on:
  push:
    branches:
      - main
      - develop
      - feature_*

  pull_request:
    branches:
      - main
      - develop
      - feature_*

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.20"

      - name: Test
        run: |
          sudo apt-get update
          sudo apt-get install -y libblkid-dev parted dosfstools libsystemd-dev
          sudo env "PATH=$PATH" go test -v ./... -failfast -coverprofile=coverage.out -covermode=atomic
          sudo chmod 666 coverage.out

      - name: Code coverage
        run: bash <(curl -s https://codecov.io/bash)

      - name: Lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: "v1.59"
